name = "Lattice2DMonteCarlo"
uuid = "faaa8aa3-7fc9-41cf-84af-9d0c24f78989"
version = "0.1.0"
authors = ["sota <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Lattice2D = "e8031020-b7ff-4f1d-bee4-f79aea4cf140"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
Lattice2D = {rev = "main", url = "https://github.com/sotashimozono/Lattice2D.jl"}

[compat]
CSV = "0.10.15"
ColorSchemes = "3.31.0"
DataFrames = "1.8.1"
Lattice2D = "0.1.1"
LinearAlgebra = "1.12.0"
Pkg = "1.12.0"
Plots = "1.41.2"
Random = "1.11.0"
Statistics = "1.11.1"
Test = "1.11.0"
