[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Lattice2D = "e8031020-b7ff-4f1d-bee4-f79aea4cf140"
Lattice2DMonteCarlo = "faaa8aa3-7fc9-41cf-84af-9d0c24f78989"

[sources]
Lattice2D = {path = "..\\..\\Lattice2D.jl"}
Lattice2DMonteCarlo = {path = ".."}
